# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 480816912941c9f346d5d06b400ac5a383af70ea56da4bb4f560eb0f9e437c66bf18384ce72d102497da3229284c0c3345d8ab93672a5a4c56f4729fbd10c857

test:
  secret_key_base: 608c8f50531ec7034920c567c244e23a6318f7250e250ad676bab93810804c6d01b6b25358bd67d44171fb8dadb72da075e7b1f257d2262ae618e4b9c198cec4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
